FROM tomcat:8.0-jre8

ENV WEBAPP_PATH /usr/local/tomcat/webapps/learnings
ENV TMP_CONF_IN_FOLDER /tmp/conf/
ENV TMP_CONF_OUT_FOLDER ${WEBAPP_PATH}/WEB-INF/classes

ARG VERSION

COPY ./docker/tomcat/conf/* $TMP_CONF_IN_FOLDER
COPY ./docker/tomcat/bin/startup /usr/bin/startup
RUN chmod 744 /usr/bin/startup

RUN mkdir ${WEBAPP_PATH}
COPY ./target/learnings-2.0a/ $WEBAPP_PATH

CMD startup
